spring:
  application:
    name: spring-boot
  profiles:
    active: dev

server:
  port: 8085

#configs:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver

# Logger config
logging:
  config: classpath:log4j2.xml
